name: 01 - Building Blocks
on: [ push, workflow_dispatch ]

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    outputs:
      harish: ${{steps.sreeja.outputs.pp_s}}
    steps:
      - name: Say hello
        id: sreeja
        run: echo "pp_s=helloworld"
      - name: to list file
        run: ls -l
  echo-goodbye:
    runs-on: ubuntu-latest
    needs: echo-hello
    steps:
      - name: call the out of the previuos job
        run: echo ${{needs.echo-hello.outputs.harish}}




  

      
